#!/bin/sh

# for debug
set -x

param1=""

# make sure the module exists
if [ ! -f ./dump_stack.ko ]; then
	echo "dump_stack.ko not found!"
	exit
fi

# get the symbol address
param1="`cat /proc/kallsyms | grep -i $1 | awk '{print $1}'`"

# get the length of the address
len=${#param1}

if [ ! $len -eq 16 ]; then
	echo "addr is not 16 digits"
	exit
fi

echo $1 is 0x$param1


#insmod dump_stack.ko long_1=0x$1 long_2=$pid
insmod dump_stack.ko long_1=0x$param1
lsmod | grep dump_stack
