#!/bin/sh
rm -rf jetcd1.etcd/
/usr/bin/etcd --name jetcd1 \
  --initial-advertise-peer-urls http://10.0.1.11:2380 \
  --listen-peer-urls http://10.0.1.11:2380 \
  --listen-client-urls http://10.0.1.11:2379,http://127.0.0.1:2379 \
  --advertise-client-urls http://10.0.1.11:2379 \
  --initial-cluster-token etcd-cluster-0 \
  --initial-cluster jetcd1=http://10.0.1.11:2380,jetcd2=http://10.0.1.12:2380,jetcd3=http://10.0.1.13:2380 \
  --initial-cluster-state new

