#docker build -t go-dev:1.5 -f Dockerfile.go1.5 .

FROM ubuntu:14.10

MAINTAINER James Ho
RUN apt-get update -y && apt-get install --no-install-recommends -y -q \
  openssh-client \
  curl \
  build-essential \
  bison \
  ca-certificates \
  git \
  mercurial \
  wget \
  vim-gnome \
  libpcap0.8-dev \
  firefox \
  graphviz \
  libc6-dbg \
  gdb

# set up go 1.4.2
RUN wget https://storage.googleapis.com/golang/go1.4.2.src.tar.gz
RUN tar -xzf go1.4.2.src.tar.gz -C /
RUN rm go1.4.2.src.tar.gz
RUN mv /go /root/go1.4
ENV GO_DISTFLAGS -s
RUN cd /root/go1.4/src && ./make.bash —no-clean 2>&1
#RUN cd /goroot/src && ./all.make —no-clean 2>&1
# http://dave.cheney.net/2012/09/08/an-introduction-to-cross-compilation-with-go

# set up go 1.5
RUN wget https://storage.googleapis.com/golang/go1.5beta2.src.tar.gz
RUN tar -xzf go1.5beta2.src.tar.gz -C /
RUN mv /go /goroot
RUN cd /goroot/src && ./make.bash —no-clean 2>&1

# clean up
RUN rm -rf /root/go1.4/
RUN rm /go1.5beta2.src.tar.gz

# config env
RUN mkdir -p /gopath/src

ENV GOROOT /goroot
ENV PATH $GOROOT/bin/:.:$PATH
ENV GOPATH /gopath

